# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "nowatchdog"
    "nvme.noacpi=1"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/58daacfb-70e3-4d98-841c-452e78bb4ef0";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
      "noatime"
    ];
  };

  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/4057d790-368f-4201-8760-3f954cd47fa9";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  boot.initrd.luks.devices."cryptaelius" = {
    device = "/dev/disk/by-uuid/fe579785-2d41-40ca-a855-816052ab0dc5";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  fileSystems."/tmpfs" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "size=3G"
      "mode=777"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/58daacfb-70e3-4d98-841c-452e78bb4ef0";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/58daacfb-70e3-4d98-841c-452e78bb4ef0";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/persist/system" = {
    device = "/dev/disk/by-uuid/58daacfb-70e3-4d98-841c-452e78bb4ef0";
    fsType = "btrfs";
    options = [
      "subvol=@system"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/persist/keep" = {
    device = "/dev/disk/by-uuid/58daacfb-70e3-4d98-841c-452e78bb4ef0";
    fsType = "btrfs";
    options = [
      "subvol=@keep"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/persist/transient" = {
    device = "/dev/disk/by-uuid/58daacfb-70e3-4d98-841c-452e78bb4ef0";
    fsType = "btrfs";
    options = [
      "subvol=@transient"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/persist/ephemeral" = {
    device = "/dev/disk/by-uuid/58daacfb-70e3-4d98-841c-452e78bb4ef0";
    fsType = "btrfs";
    options = [
      "subvol=@ephemeral"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/btr" = {
    device = "/dev/disk/by-uuid/58daacfb-70e3-4d98-841c-452e78bb4ef0";
    fsType = "btrfs";
    options = [
      "subvolid=5"
      "noatime" # never access time
    ];
  };

  fileSystems."/mnt/tomb" = {
    device = "/dev/disk/by-uuid/58daacfb-70e3-4d98-841c-452e78bb4ef0";
    fsType = "btrfs";
    options = [
      "subvol=@tombs"
      "noatime"
      # "nodatacow" # This does not work https://btrfs.readthedocs.io/en/latest/Administration.html (will set the entire system to nodatacow)
    ];
  };

  # TODO: Move this to a good spot maybe?
  systemd.tmpfiles.rules = [
    "d /mnt/tomb 0775 root users -"
    "d /mnt/tomb/tombs 0775 root users -"
    "H /mnt/tomb/tombs - - - - +C" # Nocow by default
    "d /mnt/user 0775 root users -"

    "d /mnt/aelius/media/youtube/tmp - - - 5d"
  ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/44A6-B4F8";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/58daacfb-70e3-4d98-841c-452e78bb4ef0";
    fsType = "btrfs";
    options = [
      "subvol=@swap"
      "noatime"
    ];
  };

  fileSystems."/mnt/aelius" = {
    device = "/dev/disk/by-uuid/1940c7ad-ea0f-43ac-8e7d-26b6b302d0bb";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/mnt/fluder" = {
    device = "/dev/disk/by-uuid/64C573804DD961FD";
    fsType = "ntfs-3g";
    options = [
      # "noauto"
      "uid=1000"
      "gid=100"
      "rw"
      "user"
      "exec"
      "umask=000"
      "windows_names"
    ];
  };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  zramSwap = {
    # Chonky games require a ton of ram easily accessible. I faced some crashes when this was at 50% (I only have 16 gb of ram)
    enable = true;
    algorithm = "zstd";
    priority = 5;
    memoryPercent = 25;
  };

  # Extra devices

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
